[package]
name = "openzeppelin"
version = "0.6.1"
description = "A library for secure smart contract development written in Cairo for StarkNet, a decentralized ZK Rollup."
homepage = "https://github.com/OpenZeppelin/cairo-contracts"
